import Link from 'next/link'
import { ArrowLeft, ExternalLink } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { ReceiptCheckSummary } from './receipt-check'
import { moneyText } from '@/lib/local-purchasing/evidence'
import type { SavedPurchase } from '@/lib/local-purchasing/history'
import { variantDescription } from '@/lib/products/pricing'

export function PurchaseDetail({ purchase }: { purchase: SavedPurchase }) {
  return <article className="flex min-w-0 flex-col gap-6 font-sans">
    <nav aria-label="Purchase history"><Button asChild variant="ghost" size="sm"><Link href="/dashboard/purchasing/local/history"><ArrowLeft data-icon="inline-start" />All saved purchases</Link></Button></nav>
    <header className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 flex-col gap-2"><div className="flex flex-wrap items-center gap-3"><h1 className="break-words text-2xl font-semibold">{purchase.docRef || 'Recorded purchase'}</h1><Badge variant={purchase.reviewStatus === 'verified' ? 'secondary' : 'outline'}>{purchase.reviewStatus === 'exception' ? 'Accepted exception' : purchase.reviewStatus === 'verified' ? 'Verified receipt' : 'Not document-verified'}</Badge></div><p className="text-base">{purchase.supplierName}</p><p className="text-sm text-muted-foreground">Purchase date {purchase.purchaseDate} · {purchase.lineCount} source rows</p><p className="text-sm text-muted-foreground">Recorded {purchase.createdAt.slice(0, 10)}{purchase.recordedBy ? ` by ${purchase.recordedBy}` : ''}</p></div><div className="flex flex-wrap gap-2">{purchase.orderId && <Button asChild variant="outline"><Link href={`/dashboard/purchasing/local/orders/${purchase.orderId}`}>{purchase.orderNumber} · r{purchase.orderRevision}</Link></Button>}{purchase.supplierId && <Button asChild><Link href={`/dashboard/purchasing/local/orders/new?supplier=${purchase.supplierId}`}>Reorder from this supplier</Link></Button>}</div></header>
    {purchase.exceptionReason && <Alert><AlertTitle>Buyer-accepted exception</AlertTitle><AlertDescription>{purchase.exceptionReason}</AlertDescription></Alert>}
    <Alert><AlertTitle>Purchase recorded, not a payment or stock posting</AlertTitle><AlertDescription>This view retains the amounts and product mappings used at save time. Later Inventory renames do not change the supplier wording, original evidence or saved calculation.</AlertDescription></Alert>
    {purchase.calculation ? <ReceiptCheckSummary check={purchase.calculation} /> : <Alert><AlertTitle>No saved reconciliation snapshot</AlertTitle><AlertDescription>This older record has no automatic receipt verification. Its original amounts have not been recalculated or labelled as verified.</AlertDescription></Alert>}
    <p className="text-sm leading-relaxed text-muted-foreground">{purchase.vatReclaimable ? 'Input VAT was recorded as reclaimable and kept out of comparable product cost.' : 'Input VAT was not recorded as reclaimable on this purchase.'}</p>
    <section className="flex min-w-0 flex-col gap-3" aria-label="Saved receipt items"><h2 className="text-lg font-semibold">Supplier receipt items</h2><Table><TableHeader><TableRow><TableHead>Supplier item / Inventory link</TableHead><TableHead>Code / unit</TableHead><TableHead className="text-right">Quantity</TableHead><TableHead className="text-right">Printed unit price</TableHead><TableHead className="text-right">Net / unit</TableHead><TableHead className="text-right">Payable / unit</TableHead><TableHead className="text-right">Line payable</TableHead></TableRow></TableHeader><TableBody>{purchase.lines.map((line) => <TableRow id={`receipt-line-${line.calculation?.key ?? line.id}`} key={line.id}><TableCell><p className="max-w-sm whitespace-normal break-words font-medium">{line.supplierLabel}</p><p className="max-w-sm whitespace-normal text-sm text-muted-foreground">Inventory: {line.productName || (line.productId ? 'Unavailable product' : 'Not linked')}</p>{(line.productId || line.variantSnapshot) && <p className="text-sm text-muted-foreground">{variantDescription(line.variantSnapshot)}{line.variantSnapshot && !line.variantId ? ' (removed from Inventory; original identity retained)' : ''}{line.variantSnapshot?.provenance === 'manual' ? ' · Variant chosen by buyer' : line.variantSnapshot ? ` · From ${line.variantSnapshot.provenance === 'order' ? 'issued order' : 'saved supplier item'}` : ''}</p>}<p className="text-sm text-muted-foreground">{line.matchMethod === 'auto' ? 'Automatically linked' : line.productId ? 'Buyer-linked product' : 'Supplier wording only'}</p></TableCell><TableCell>{line.supplierCode || '—'}<p className="text-sm text-muted-foreground">{line.unit || 'Not stated'}</p></TableCell><TableCell className="text-right font-mono">{line.qty}</TableCell><TableCell className="text-right font-mono">{line.printedUnitPrice == null ? 'Not printed' : moneyText(line.printedUnitPrice)}</TableCell><TableCell className="text-right font-mono">{line.unitPriceNet == null ? 'Not recorded' : moneyText(line.unitPriceNet)}</TableCell><TableCell className="text-right font-mono">{line.calculation ? moneyText(line.calculation.rawPayable / line.qty) : 'Not recorded'}</TableCell><TableCell className="text-right font-mono">{line.calculation ? moneyText(line.calculation.payable) : 'Not recorded'}</TableCell></TableRow>)}</TableBody></Table></section>
    <section className="flex flex-col gap-3" aria-label="Original supplier documents"><h2 className="text-lg font-semibold">Original evidence</h2>{purchase.documents.length ? <ul className="flex flex-col gap-3">{purchase.documents.map((document) => <li key={document.id}><div className="flex flex-wrap items-center justify-between gap-3"><p className="break-words text-sm">{document.fileName} · {document.source === 'sheet' ? 'Spreadsheet parsed directly' : 'Document transcription retained'}</p>{document.url ? <Button asChild variant="outline" size="sm"><a href={document.url} target="_blank" rel="noopener noreferrer"><ExternalLink data-icon="inline-start" />View original</a></Button> : <p className="text-sm text-muted-foreground">File link unavailable. Reload to retry.</p>}</div>{Boolean(document.comparison?.differences.length) && <details className="py-3"><summary className="cursor-pointer text-sm font-medium">Accepted differences from the issued order</summary><ul className="flex flex-col gap-3 py-3 text-sm leading-relaxed">{document.comparison!.differences.map((difference, index) => <li key={index}>{difference.message}{difference.expected != null && <> Expected: {difference.expected}. Actual: {difference.actual ?? 'not stated'}.</>}</li>)}</ul></details>}</li>)}</ul> : <p className="text-sm text-muted-foreground">No original file was attached to this purchase. The buyer-entered evidence and review are retained.</p>}</section>
    {purchase.notes && <section className="flex flex-col gap-2"><h2 className="text-lg font-semibold">Purchase notes</h2><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{purchase.notes}</p></section>}
  </article>
}
